### ISSUE TITLE
Getting the issue while using the Abstract class.

### ISSUE THREAD

**Issue by harshalizode** [tarsil/mongoz#29]
Hello,
I have a models as:
```
class BaseDocument(mongoz.Document):
    """
    The base document for all documents using the `registry` registry.
    """
    objects: ClassVar[CustomManger] = CustomManger()

    class Meta:
        """
            It contains the Meta information related the database for \
                each model level.
        """
        abstract = True
        registry = settings.client
        database = settings.db
```
```
class Employee(BaseDocument):
    month_period: int = mongoz.Integer(null=True)
    full_name: str = mongoz.String()
    employee_code: str = mongoz.String()
    date_of_joining: datetime.datetime = mongoz.DateTime(null=True)
    e_mail: str = mongoz.String(null=True)
    mobile_no: str = mongoz.String(null=True)
```

When I am trying to query into db, Its using the default manager i.e. "Manager" object, instead of "CustomManager".

If I again initialize the "objects" in the Employee Document and try to query as:

`Employee.objects.create(full_name='Emp_Name_1326', employee_code='01326')`

Then, it returns the API response as:
```
{
    "detail": [
        {
            "type": "missing",
            "loc": [
                "month_period"
            ],
            "msg": "Field required",
            "input": {
                "full_name": "Emp_Name_1326",
                "employee_code": "01326"
            },
            "url": "https://errors.pydantic.dev/2.6/v/missing"
        },
        {
            "type": "missing",
            "loc": [
                "date_of_joining"
            ],
            "msg": "Field required",
            "input": {
                "full_name": "Emp_Name_1326",
                "employee_code": "01326"
            },
            "url": "https://errors.pydantic.dev/2.6/v/missing"
        },
        {
            "type": "missing",
            "loc": [
                "e_mail"
            ],
            "msg": "Field required",
            "input": {
                "full_name": "Emp_Name_1326",
                "employee_code": "01326"
            },
            "url": "https://errors.pydantic.dev/2.6/v/missing"
        },
        {
            "type": "missing",
            "loc": [
                "mobile_no"
            ],
            "msg": "Field required",
            "input": {
                "full_name": "Emp_Name_1326",
                "employee_code": "01326"
            },
            "url": "https://errors.pydantic.dev/2.6/v/missing"
        }
    ]
}

```

Can you help me for this?
Is somthing wrong here?
Thank you.

**Comment by tarsil** [comment]
@harshalizode Mongoz actually does not support custom managers, at least I did not add those and I think this would require some additional implementation.

When you use the default "manager". Does it work properly? I would assume so which means if you want an additional manager or custom, that would require to create a feature that supports it.

Edgy and Saffier do support it and for mongoz there was never the case of that need but we can add it, for sure.

**Comment by harshalizode** [comment]
No, when I commented the CustomManager in the BaseDocument, the behaviour remained the same.

**Comment by tarsil** [comment]
Ok a couple of questions.

1. If the class is not abstract, does it work with the manager and custom manager?

Because then its something that needs to be addressed in the abstract class for sure

**Comment by harshalizode** [comment]
Yes, with non abstract class it is working. I just created the Abstract class to override Manager object and for the meta class.

**Comment by tarsil** [comment]
Ok. So a fix needs to be done for abstract classes. Thank you for this

**Comment by harshalizode** [comment]
yes.

**Comment by tarsil** [comment]
Ok. I will look into it. Thank you for this @harshalizode

**Comment by tarsil** [comment]
@harshalizode found the issue. It was not in the abstract class. it was a missing validation. I had it in the past and somehow I had a regression. I will do a release soon.

**Comment by tarsil** [comment]
@harshalizode my friend. Release 0.7.0 done now. Thank you so much for your inputs on this. Something clearly missing there and as a bonus. Just because you are such a fantastic contributor.

https://mongoz.tarsild.io/managers/

This is new and I hope you enjoy :)

**Comment by harshalizode** [comment]
Okay, thanks for the rapid resolution response.

**Comment by harshalizode** [comment]
Yes, the Abstract class is now functional; but while we may inherit the "CustomManager" at the model level, it cannot inherit the "CustomManager". Each model must additionally have its CustomManager initialized at the model level.

**Comment by tarsil** [comment]
@harshalizode thank you very much for this. This is something we might want to look in the future and allow different ways, perhaps? 

Oh, the PR you opened, did you manage to install the requirements and runs the scripts?

**Comment by tarsil** [comment]
@harshalizode although I'm not 100% sure if I understood your side. 

Check this one one. We are actually using the inheritance of QuerySetManager here as per new feature added.

https://github.com/tarsil/mongoz/blob/main/tests/test_managers.py

**Comment by harshalizode** [comment]
Okay, I'll look into this, and for PR, I'll install the requirements to run the script and get back to you.
Thank you.
